version: '3.9'

services:
  ui:
    image: andreclerigo/payload-dashboard-ui:latest-arm64-build
    pull_policy: always
    container_name: ui
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
